services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=teste_tech
    networks:
      - spring-network

  spring-app:
    build: ./backend
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/teste_tech
    depends_on:
      - mongodb
    networks:
      - spring-network

  frontend:
    build: ./frontend/order-management
    container_name: order-management-frontend
    ports:
      - "3000:80"
    depends_on:
      - spring-app
    networks:
      - spring-network

volumes:
  mongodb_data:
    driver: local

networks:
  spring-network:
    driver: bridge